---
- name: caller
  hosts: vyos
  gather_facts: false

  tasks:
    - name: import measure_drop
      import_role:
        name: measure_drop

    - name: block when is_dropped true 
      block:
        - name: import get_bandwidth_policy
          import_role:
            name: get_bandwidth_policy

        - name: import make_config
          import_role:
            name: make_config

        - name: import set_config
          import_role:
            name: set_config
      when: is_dropped
