---
- name: get_dropped
  hosts: localhost
  gather_facts: false
  vars:
    sample_arp: |
      Address                  HWtype  HWaddress           Flags Mask            Iface
      192.168.1.2              ether   02:42:c0:a8:01:02   C                     eth1
      192.168.2.2              ether   02:42:c0:a8:02:02   C                     eth2

    sample_queue: |
      qdisc noqueue 0: root refcnt 2
       Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
       backlog 0b 0p requeues 0
      qdisc ingress ffff: parent ffff:fff1 ----------------
       Sent 29490278728 bytes 737257163 pkt (dropped 736983912, overlimits 0 requeues 0)
       backlog 0b 0p requeues 0

  tasks:
    # - name: show commands
    #   vyos_command:
    #     # commands: "show interfaces ethernet eth1 queue"
    #     commands: "show arp"
    #   register: result

    # - name: debug
    #   debug:
    #     var: result.stdout_lines[0]

    # - name: parse
    #   debug:
    #     var: sample_arp | parse_cli_textfsm('./vyatta_vyos_show_arp.textfsm')

    - name: parse
      debug:
        var: sample_queue | parse_cli_textfsm('./vyatta_vyos_show_interfaces_ethernet_name_queue.textfsm')
