---
- name: get_dropped
  hosts: localhost
  gather_facts: false
  vars:
    bandwidth_policy_list:
    - qos_in_1k
    - qos_in_50k
    - qos_in_100k
    - qos_in_500k
    - qos_in_1m
    - qos_in_10m


  tasks:
    - name: get current bandwidth policy
      set_fact:
        current_bandwidth_policy_index: "{{ bandwidth_policy_list.index(bandwidth_policy[0]['POLICY']) }}"
      vars:
        text: "set interfaces ethernet eth1 traffic-policy in 'qos_in_1k"
        bandwidth_policy: "{{ text | parse_cli_textfsm('./bandwidth_policy_parse.textfsm') }}"

    - name: debug
      debug:
        msg: "set interfaces ethernet eth1 traffic-policy in {{ next_bandwidth_policy }}"
      vars:
        next_bandwidth_policy: "{{ bandwidth_policy_list[current_bandwidth_policy_index | int + 1] }}"
