---
- name: get_dropped
  hosts: vyos
  gather_facts: false

  tasks:
    - name: show command
      vyos_command:
        commands: 
          - "show interfaces ethernet eth1 queue"
      register: result

    - name: debug
      debug:
        var: parsed_dropped | json_query(query_string)
      vars:
        parsed_dropped: "{{ result.stdout[0] | parse_cli_textfsm('./vyos_interface_queue.textfsm') }}"
        query_string: "[?TYPE=='ingress']"
