---
- name: show commands
  vyos_command:
    commands: "show configuration commands | match 'eth1 traffic-policy in'"
  register: config_bandwidth_policy

- name: get current bandwidth policy
  set_fact:
    current_bandwidth_policy: "{{ config_bandwidth_policy.stdout[0] | parse_cli_textfsm(template_path) }}"
  vars:
    template_path: "{{ role_path }}/files/bandwidth_policy_parse.textfsm"

- name: get current bandwidth policy index
  set_fact:
    current_bandwidth_policy_index: "{{ bandwidth_policy_list.index(current_bandwidth_policy[0]['POLICY']) }}"

- name: debug vars
  debug:
    msg: "{{ item }}"
  loop:
    - "current_bandwidth_policy: {{ current_bandwidth_policy }}"
    - "current_bandwidth_policy_index: {{ current_bandwidth_policy_index }}"
