---
- name: show commands
  vyos_command:
    commands: 
      - "show interfaces ethernet eth1 queue"
      - "show interfaces ethernet eth1 queue"
  register: show_interfaces_ethernet_eth1_queue

- name: set ingress_drop
  set_fact:
    ingress_drop: "{{ ingress_drop | default([]) + parsed | json_query(query_string) }}"
  vars:
    template_path: "{{ role_path }}/files/vyos_interface_queue.textfsm"
    parsed: "{{ item | parse_cli_textfsm(template_path) }}"
    query_string: "[?TYPE=='ingress'].DROPPED"
  loop: "{{ show_interfaces_ethernet_eth1_queue.stdout }}"

- name: set is_dropped
  set_fact:
    is_dropped: "{{ ingress_drop[0] | int < ingress_drop[1] | int }}"

- name: debug vars
  debug:
    msg: "{{ item }}"
  loop:
    - "prev_drop: {{ ingress_drop[0] }}"
    - "last_drop: {{ ingress_drop[1] }}"
    - "is_dropedd: {{ is_dropped }}"
