---
- name: show commands
  vyos_command:
    commands: "show configuration commands | match 'eth1 traffic-policy in'"
  register: config_bandwidth_policy

- name: get current bandwidth policy
  set_fact:
    current_bandwidth_policy: "{{ parsed[0]['POLICY'] }}"
  vars:
    template_path: "{{ role_path }}/files/vyos_bandwidth_policy.textfsm"
    parsed: "{{ config_bandwidth_policy.stdout[0] | parse_cli_textfsm(template_path) }}"

- name: set current bandwidth policy index
  set_fact:
    current_bandwidth_policy_index: "{{ bandwidth_policy_list.index(current_bandwidth_policy) }}" 

- name: debug vars
  debug:
    msg: "{{ item }}"
  loop:
    - "{{ current_bandwidth_policy_index | int }}"
    - "{{ bandwidth_policy_list | length -1 }}"

- name: assert maximum bandwidth
  assert:
    that:
      - "{{ current_bandwidth_policy_index | int != bandwidth_policy_list | length -1 }}"
    msg: "current bandwidth is max"

- name: get next bandwidth policy
  set_fact:
    next_bandwidth_policy: "{{ bandwidth_policy_list[next_bandwidth_policy_index | int] }}"
  vars:
    next_bandwidth_policy_index: "{{ current_bandwidth_policy_index | int + 1}}"

- name: debug vars
  debug:
    msg: "{{ item }}"
  loop:
    - "current_bandwidth_policy: {{ current_bandwidth_policy }}"
    - "next_bandwidth_policy: {{ next_bandwidth_policy }}"
